### ISSUE TITLE
Message count calculation issue

### ISSUE THREAD

**Issue by SiweiWang** [rama-nallamilli/kafka-prometheus-monitoring#4]
Current message count is calculated using LogEndOffSet

in Kafka.xml
`- pattern : kafka.log<type=Log, name=LogEndOffset, topic=(.+), partition=(.+)><>Value
`

in dashboard.json
```
          "targets": [
            {
              "expr": "kafka_log_log_value{topic=\"customer\"}",
              "intervalFactor": 2,
              "legendFormat": "",
              "metric": "",
              "refId": "A",
              "step": 20
            }
```
However, to correctly calculate number of message, it should use LogEndOffset - LogStartOffset .

**Comment by SiweiWang** [comment]
@rama-nallamilli fix is in this PR https://github.com/rama-nallamilli/kafka-prometheus-monitoring/pull/5

**Comment by rama-nallamilli** [comment]
Thank you for the fix @SiweiWang
